/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteRouteImport } from './routes/leaderboard/route'
import { Route as FormulaRouteRouteImport } from './routes/formula/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as UUsernameRouteRouteImport } from './routes/u/$username/route'
import { Route as AdminComponentsRouteRouteImport } from './routes/admin/components/route'

const LeaderboardRouteRoute = LeaderboardRouteRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaRouteRoute = FormulaRouteRouteImport.update({
  id: '/formula',
  path: '/formula',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRouteRoute = UUsernameRouteRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComponentsRouteRoute = AdminComponentsRouteRouteImport.update({
  id: '/admin/components',
  path: '/admin/components',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/formula': typeof FormulaRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/admin/components': typeof AdminComponentsRouteRoute
  '/u/$username': typeof UUsernameRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/formula': typeof FormulaRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/admin/components': typeof AdminComponentsRouteRoute
  '/u/$username': typeof UUsernameRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/formula': typeof FormulaRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/admin/components': typeof AdminComponentsRouteRoute
  '/u/$username': typeof UUsernameRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formula'
    | '/leaderboard'
    | '/admin/components'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formula' | '/leaderboard' | '/admin/components' | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/formula'
    | '/leaderboard'
    | '/admin/components'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  FormulaRouteRoute: typeof FormulaRouteRoute
  LeaderboardRouteRoute: typeof LeaderboardRouteRoute
  AdminComponentsRouteRoute: typeof AdminComponentsRouteRoute
  UUsernameRouteRoute: typeof UUsernameRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formula': {
      id: '/formula'
      path: '/formula'
      fullPath: '/formula'
      preLoaderRoute: typeof FormulaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/components': {
      id: '/admin/components'
      path: '/admin/components'
      fullPath: '/admin/components'
      preLoaderRoute: typeof AdminComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  FormulaRouteRoute: FormulaRouteRoute,
  LeaderboardRouteRoute: LeaderboardRouteRoute,
  AdminComponentsRouteRoute: AdminComponentsRouteRoute,
  UUsernameRouteRoute: UUsernameRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
